apiVersion: v1
kind: Service

metadata:
  name: backend-service

spec:
  type: LoadBalancer

  selector:
    app: whatsapp-backend

  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020