apiVersion: apps/v1
kind: Deployment

metadata:
  name: whatsapp-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: whatsapp-backend

  template:
    metadata:
      labels:
        app: whatsapp-backend

    spec:
      containers:
        - name: backend

          image: whatssapp_clone-backend

          imagePullPolicy: Never

          ports:
            - containerPort: 3020

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"